### ISSUE TITLE
obj file in rendermodels/ missing

### ISSUE THREAD

**Issue by skedaddleconnect** [spayne/right_hand_test#1]
Hello,

Thank you very much for this repo.

I was just taking a look at the files and saw that in `resources/rendermodels/right_hand_test` that there were files which included a `.mtl` and `.png`, but the obj file associated with them was missing (perhaps as `.obj` is included in the gitignore?)

Also, I can see that the bone positions for the right hand are pre-programmed, are there also bone positions for the left hand as well?

Thank you very much.

**Comment by spayne** [comment]
you were correct about the .gitignore file.  I removed the obj filter and pushed the obj file.

The bone positions are for the right hand only.  I extracted them with a small program that grabbed them from the index controller.

My intention for this driver was to make it as small as possible (there is another driver I've written called soft_knuckles that does a bit more).  

Anyway thanks for finding that.  Let me know if you need help (or the left hand!)

**Comment by skedaddleconnect** [comment]
awesome, thank you!

If it's possible, it would be great to get the left hand positions as well - I don't quite know how I would be able to extract the positions myself..

Thanks again :)

**Comment by skedaddleconnect** [comment]
ah - I just checked out the soft_knuckles repo and looks like the left hand positions are there.

Thank you very much.

**Comment by spayne** [comment]
Glad you found it.   

I want 'right_hand_test' to be as minimal as possible... To add left hand side, I was thinking of adding just some instructions on how to do it.  So please let me know if soft_knuckles works as a reference for you.

**Comment by skedaddleconnect** [comment]
im sorry if this isn't really in the scope of the project - but I was looking at adding the second controller, by creating a new instance of the `RightHandTest` class and assigning it with a new controller by `TrackedDeviceAdded`, which all seems to work.

However, when I try to turn on my controllers which come with the headset, after starting steamvr (I'm getting the positioning from them for the virtual controllers), games default to using the left virtual controller, with the right (oculus) controller. Is there anything that I need to do to fix that?

Both sets of controllers show up in the steamvr overlay, but then steamvr home and other games seem to choose a controller from each set - do they have some sort of selection priority, and if so, is it possible to make steamvr choose a specific controller pair over another?

Thank you very much.

**Comment by skedaddleconnect** [comment]
ah - got it, the controller needed to be activated for it to be picked up instead of one of the other controllers.

**Comment by spayne** [comment]
By 'activate' do you mean something in the bindings/steamvr UI?

It's been awhile for me - my recollection is that the system supports multiple simultaneous controllers since I was using a vive tracker as a controller as well as another custom controller that polled the tracker (so for two hands there would be four 'controllers' showing up).  However I also used to power off  any controllers I didn't want - so I suspect there is a possibility of conflict - but this may have been to just keep things simpler for myself and the users.

**Comment by skedaddleconnect** [comment]
sorry, wasn't very clear - what I've found is that in steamvr, and steamvr games, is that they pick the controllers that are moving (ie. they aren't in standby) - so in the project, a physical controller would override the virtual controller due to the virtual controller not moving (or that is what I think causes it...).

Even so, thank you so much for this repo, as well as soft_knuckles - they are a great help!
